name: mgs2amr
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - sqlite=3
  - r-base=4.2    # ensure Rscript 4+
  - r-tidyverse
  - r-rsqlite
  - r-igraph
  - r-foreach
  - r-doparallel
  - r-seqinr
  - usearch=11
  - blast=2.16    # includes blastn
  - pigz          # optional, but multi-threaded gzip
  - metacherchant # if available via bioconda (else install manually)
  - git
